version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "80:3000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  db_data:
